---
- hosts: ceph
  remote_user: root
  vars_files:
  - variables
  - my_vault.yaml
  tasks:

  - name: Agregar usuario {{User_ceph}}
    user:
      name: "{{User_ceph}}"
      password: "{{ my_password | password_hash('sha512') }}"
      shell: /bin/bash
      createhome: yes
      home: /home/{{User_ceph}}
      append: yes